# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tftg256-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/DPAWS/Documents/CHRIS/Countermeasures/CR_32/fpga/vivado_examples/aes128_verilog.cache/wt [current_project]
set_property parent.project_path C:/Users/DPAWS/Documents/CHRIS/Countermeasures/CR_32/fpga/vivado_examples/aes128_verilog.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/DPAWS/Documents/CHRIS/Countermeasures/CR_32/fpga/vivado_examples/aes128_verilog.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs C:/Users/DPAWS/Documents/CHRIS/Countermeasures/CR_32/fpga/vivado_examples/aes128_verilog/aes128_verilog.srcs/sources_1/new [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/DPAWS/Documents/CHRIS/Countermeasures/CR_32/fpga/vivado_examples/aes128_verilog.srcs/sources_1/imports/fpga/cryptosrc/aes_googlevault/aes_core.v
  C:/Users/DPAWS/Documents/CHRIS/Countermeasures/CR_32/fpga/vivado_examples/aes128_verilog.srcs/sources_1/imports/fpga/cryptosrc/aes_googlevault/aes_ks.v
  C:/Users/DPAWS/Documents/CHRIS/Countermeasures/CR_32/fpga/vivado_examples/aes128_verilog.srcs/sources_1/imports/fpga/cryptosrc/aes_googlevault/aes_sbox.v
  C:/Users/DPAWS/Documents/CHRIS/Countermeasures/CR_32/fpga/vivado_examples/aes128_verilog.srcs/sources_1/new/clk_randomizer.v
  C:/Users/DPAWS/Documents/CHRIS/Countermeasures/CR_32/fpga/vivado_examples/aes128_verilog.srcs/sources_1/imports/fpga/common/registers/registers.v
  C:/Users/DPAWS/Documents/CHRIS/Countermeasures/CR_32/fpga/vivado_examples/aes128_verilog.srcs/sources_1/imports/fpga/common/usb_module.v
  C:/Users/DPAWS/Documents/CHRIS/Countermeasures/CR_32/fpga/vivado_examples/aes128_verilog.srcs/sources_1/imports/fpga/common/cw305_top.v
}
read_ip -quiet C:/Users/DPAWS/Documents/CHRIS/Countermeasures/CR_32/fpga/vivado_examples/aes128_verilog.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/DPAWS/Documents/CHRIS/Countermeasures/CR_32/fpga/vivado_examples/aes128_verilog.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DPAWS/Documents/CHRIS/Countermeasures/CR_32/fpga/vivado_examples/aes128_verilog.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DPAWS/Documents/CHRIS/Countermeasures/CR_32/fpga/vivado_examples/aes128_verilog.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files C:/Users/DPAWS/Documents/CHRIS/Countermeasures/CR_32/fpga/vivado_examples/aes128_verilog.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/DPAWS/Documents/CHRIS/Countermeasures/CR_32/fpga/vivado_examples/aes128_verilog.srcs/constrs_1/imports/common/cw305_main.xdc
set_property used_in_implementation false [get_files C:/Users/DPAWS/Documents/CHRIS/Countermeasures/CR_32/fpga/vivado_examples/aes128_verilog.srcs/constrs_1/imports/common/cw305_main.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
